[profile.default]
src = "src"
test = "forge-test"
script = "forge-script"
out = "out"
libs = []
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
